/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FurnitureIndexRouteImport } from './routes/furniture/index'
import { Route as FoodIndexRouteImport } from './routes/food/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as FurnitureIdRouteImport } from './routes/furniture/$id'
import { Route as FoodOffersRouteImport } from './routes/food/offers'
import { Route as FoodFavouritesRouteImport } from './routes/food/favourites'
import { Route as FoodDishesRouteImport } from './routes/food/dishes'
import { Route as FoodCheckoutRouteImport } from './routes/food/checkout'
import { Route as FoodCartRouteImport } from './routes/food/cart'
import { Route as DebugPhpModeRouteImport } from './routes/debug.php-mode'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedOutletRouteImport } from './routes/_authenticated/outlet'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedPartnerIndexRouteImport } from './routes/_authenticated/partner/index'
import { Route as AuthenticatedOutletIndexRouteImport } from './routes/_authenticated/outlet/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as FoodRSlugRouteImport } from './routes/food/r.$slug'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedPartnerProfileRouteImport } from './routes/_authenticated/partner/profile'
import { Route as AuthenticatedPartnerPayoutsRouteImport } from './routes/_authenticated/partner/payouts'
import { Route as AuthenticatedPartnerOutletsRouteImport } from './routes/_authenticated/partner/outlets'
import { Route as AuthenticatedPartnerOrdersRouteImport } from './routes/_authenticated/partner/orders'
import { Route as AuthenticatedPartnerMenuRouteImport } from './routes/_authenticated/partner/menu'
import { Route as AuthenticatedPartnerManagersRouteImport } from './routes/_authenticated/partner/managers'
import { Route as AuthenticatedOutletRefundsRouteImport } from './routes/_authenticated/outlet/refunds'
import { Route as AuthenticatedOutletOrdersRouteImport } from './routes/_authenticated/outlet/orders'
import { Route as AuthenticatedOutletMenuRouteImport } from './routes/_authenticated/outlet/menu'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedFoodOrdersRouteImport } from './routes/_authenticated/food.orders'
import { Route as AuthenticatedAdminWarehousesRouteImport } from './routes/_authenticated/admin/warehouses'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminRidersRouteImport } from './routes/_authenticated/admin/riders'
import { Route as AuthenticatedAdminRestaurantsRouteImport } from './routes/_authenticated/admin/restaurants'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRefundsVerifyRouteImport } from './routes/_authenticated/admin/refunds-verify'
import { Route as AuthenticatedAdminRefundsRouteImport } from './routes/_authenticated/admin/refunds'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin/partners'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminOfferTilesRouteImport } from './routes/_authenticated/admin/offer-tiles'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin/inventory'
import { Route as AuthenticatedAdminHeroSlidesRouteImport } from './routes/_authenticated/admin/hero-slides'
import { Route as AuthenticatedAdminFurniturePromosRouteImport } from './routes/_authenticated/admin/furniture-promos'
import { Route as AuthenticatedAdminFurnitureRouteImport } from './routes/_authenticated/admin/furniture'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedOrdersIdInvoiceRouteImport } from './routes/_authenticated/orders.$id.invoice'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnitureIndexRoute = FurnitureIndexRouteImport.update({
  id: '/furniture/',
  path: '/furniture/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/food/',
  path: '/food/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnitureIdRoute = FurnitureIdRouteImport.update({
  id: '/furniture/$id',
  path: '/furniture/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodOffersRoute = FoodOffersRouteImport.update({
  id: '/food/offers',
  path: '/food/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodFavouritesRoute = FoodFavouritesRouteImport.update({
  id: '/food/favourites',
  path: '/food/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodDishesRoute = FoodDishesRouteImport.update({
  id: '/food/dishes',
  path: '/food/dishes',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodCheckoutRoute = FoodCheckoutRouteImport.update({
  id: '/food/checkout',
  path: '/food/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodCartRoute = FoodCartRouteImport.update({
  id: '/food/cart',
  path: '/food/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugPhpModeRoute = DebugPhpModeRouteImport.update({
  id: '/debug/php-mode',
  path: '/debug/php-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutletRoute = AuthenticatedOutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartnerIndexRoute =
  AuthenticatedPartnerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedOutletIndexRoute =
  AuthenticatedOutletIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOutletRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const FoodRSlugRoute = FoodRSlugRouteImport.update({
  id: '/food/r/$slug',
  path: '/food/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPartnerProfileRoute =
  AuthenticatedPartnerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerPayoutsRoute =
  AuthenticatedPartnerPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerOutletsRoute =
  AuthenticatedPartnerOutletsRouteImport.update({
    id: '/outlets',
    path: '/outlets',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerOrdersRoute =
  AuthenticatedPartnerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerMenuRoute =
  AuthenticatedPartnerMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerManagersRoute =
  AuthenticatedPartnerManagersRouteImport.update({
    id: '/managers',
    path: '/managers',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedOutletRefundsRoute =
  AuthenticatedOutletRefundsRouteImport.update({
    id: '/refunds',
    path: '/refunds',
    getParentRoute: () => AuthenticatedOutletRoute,
  } as any)
const AuthenticatedOutletOrdersRoute =
  AuthenticatedOutletOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedOutletRoute,
  } as any)
const AuthenticatedOutletMenuRoute = AuthenticatedOutletMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedOutletRoute,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedFoodOrdersRoute = AuthenticatedFoodOrdersRouteImport.update({
  id: '/food/orders',
  path: '/food/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminWarehousesRoute =
  AuthenticatedAdminWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRidersRoute =
  AuthenticatedAdminRidersRouteImport.update({
    id: '/riders',
    path: '/riders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantsRoute =
  AuthenticatedAdminRestaurantsRouteImport.update({
    id: '/restaurants',
    path: '/restaurants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRefundsVerifyRoute =
  AuthenticatedAdminRefundsVerifyRouteImport.update({
    id: '/refunds-verify',
    path: '/refunds-verify',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRefundsRoute =
  AuthenticatedAdminRefundsRouteImport.update({
    id: '/refunds',
    path: '/refunds',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOfferTilesRoute =
  AuthenticatedAdminOfferTilesRouteImport.update({
    id: '/offer-tiles',
    path: '/offer-tiles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeroSlidesRoute =
  AuthenticatedAdminHeroSlidesRouteImport.update({
    id: '/hero-slides',
    path: '/hero-slides',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFurniturePromosRoute =
  AuthenticatedAdminFurniturePromosRouteImport.update({
    id: '/furniture-promos',
    path: '/furniture-promos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFurnitureRoute =
  AuthenticatedAdminFurnitureRouteImport.update({
    id: '/furniture',
    path: '/furniture',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedOrdersIdInvoiceRoute =
  AuthenticatedOrdersIdInvoiceRouteImport.update({
    id: '/invoice',
    path: '/invoice',
    getParentRoute: () => AuthenticatedOrdersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/outlet': typeof AuthenticatedOutletRouteWithChildren
  '/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/debug/php-mode': typeof DebugPhpModeRoute
  '/food/cart': typeof FoodCartRoute
  '/food/checkout': typeof FoodCheckoutRoute
  '/food/dishes': typeof FoodDishesRoute
  '/food/favourites': typeof FoodFavouritesRoute
  '/food/offers': typeof FoodOffersRoute
  '/furniture/$id': typeof FurnitureIdRoute
  '/p/$id': typeof PIdRoute
  '/food/': typeof FoodIndexRoute
  '/furniture/': typeof FurnitureIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/furniture': typeof AuthenticatedAdminFurnitureRoute
  '/admin/furniture-promos': typeof AuthenticatedAdminFurniturePromosRoute
  '/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/offer-tiles': typeof AuthenticatedAdminOfferTilesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/refunds-verify': typeof AuthenticatedAdminRefundsVerifyRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsRoute
  '/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/food/orders': typeof AuthenticatedFoodOrdersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/outlet/menu': typeof AuthenticatedOutletMenuRoute
  '/outlet/orders': typeof AuthenticatedOutletOrdersRoute
  '/outlet/refunds': typeof AuthenticatedOutletRefundsRoute
  '/partner/managers': typeof AuthenticatedPartnerManagersRoute
  '/partner/menu': typeof AuthenticatedPartnerMenuRoute
  '/partner/orders': typeof AuthenticatedPartnerOrdersRoute
  '/partner/outlets': typeof AuthenticatedPartnerOutletsRoute
  '/partner/payouts': typeof AuthenticatedPartnerPayoutsRoute
  '/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/food/r/$slug': typeof FoodRSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/outlet/': typeof AuthenticatedOutletIndexRoute
  '/partner/': typeof AuthenticatedPartnerIndexRoute
  '/orders/$id/invoice': typeof AuthenticatedOrdersIdInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/account': typeof AuthenticatedAccountRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/debug/php-mode': typeof DebugPhpModeRoute
  '/food/cart': typeof FoodCartRoute
  '/food/checkout': typeof FoodCheckoutRoute
  '/food/dishes': typeof FoodDishesRoute
  '/food/favourites': typeof FoodFavouritesRoute
  '/food/offers': typeof FoodOffersRoute
  '/furniture/$id': typeof FurnitureIdRoute
  '/p/$id': typeof PIdRoute
  '/food': typeof FoodIndexRoute
  '/furniture': typeof FurnitureIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/furniture': typeof AuthenticatedAdminFurnitureRoute
  '/admin/furniture-promos': typeof AuthenticatedAdminFurniturePromosRoute
  '/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/offer-tiles': typeof AuthenticatedAdminOfferTilesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/refunds-verify': typeof AuthenticatedAdminRefundsVerifyRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsRoute
  '/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/food/orders': typeof AuthenticatedFoodOrdersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/outlet/menu': typeof AuthenticatedOutletMenuRoute
  '/outlet/orders': typeof AuthenticatedOutletOrdersRoute
  '/outlet/refunds': typeof AuthenticatedOutletRefundsRoute
  '/partner/managers': typeof AuthenticatedPartnerManagersRoute
  '/partner/menu': typeof AuthenticatedPartnerMenuRoute
  '/partner/orders': typeof AuthenticatedPartnerOrdersRoute
  '/partner/outlets': typeof AuthenticatedPartnerOutletsRoute
  '/partner/payouts': typeof AuthenticatedPartnerPayoutsRoute
  '/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/food/r/$slug': typeof FoodRSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/outlet': typeof AuthenticatedOutletIndexRoute
  '/partner': typeof AuthenticatedPartnerIndexRoute
  '/orders/$id/invoice': typeof AuthenticatedOrdersIdInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/outlet': typeof AuthenticatedOutletRouteWithChildren
  '/_authenticated/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/debug/php-mode': typeof DebugPhpModeRoute
  '/food/cart': typeof FoodCartRoute
  '/food/checkout': typeof FoodCheckoutRoute
  '/food/dishes': typeof FoodDishesRoute
  '/food/favourites': typeof FoodFavouritesRoute
  '/food/offers': typeof FoodOffersRoute
  '/furniture/$id': typeof FurnitureIdRoute
  '/p/$id': typeof PIdRoute
  '/food/': typeof FoodIndexRoute
  '/furniture/': typeof FurnitureIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/furniture': typeof AuthenticatedAdminFurnitureRoute
  '/_authenticated/admin/furniture-promos': typeof AuthenticatedAdminFurniturePromosRoute
  '/_authenticated/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/offer-tiles': typeof AuthenticatedAdminOfferTilesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/_authenticated/admin/refunds-verify': typeof AuthenticatedAdminRefundsVerifyRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/restaurants': typeof AuthenticatedAdminRestaurantsRoute
  '/_authenticated/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/_authenticated/food/orders': typeof AuthenticatedFoodOrdersRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/_authenticated/outlet/menu': typeof AuthenticatedOutletMenuRoute
  '/_authenticated/outlet/orders': typeof AuthenticatedOutletOrdersRoute
  '/_authenticated/outlet/refunds': typeof AuthenticatedOutletRefundsRoute
  '/_authenticated/partner/managers': typeof AuthenticatedPartnerManagersRoute
  '/_authenticated/partner/menu': typeof AuthenticatedPartnerMenuRoute
  '/_authenticated/partner/orders': typeof AuthenticatedPartnerOrdersRoute
  '/_authenticated/partner/outlets': typeof AuthenticatedPartnerOutletsRoute
  '/_authenticated/partner/payouts': typeof AuthenticatedPartnerPayoutsRoute
  '/_authenticated/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/food/r/$slug': typeof FoodRSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/outlet/': typeof AuthenticatedOutletIndexRoute
  '/_authenticated/partner/': typeof AuthenticatedPartnerIndexRoute
  '/_authenticated/orders/$id/invoice': typeof AuthenticatedOrdersIdInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/login'
    | '/order-success'
    | '/search'
    | '/support'
    | '/wishlist'
    | '/account'
    | '/admin'
    | '/notifications'
    | '/orders'
    | '/outlet'
    | '/partner'
    | '/c/$slug'
    | '/debug/php-mode'
    | '/food/cart'
    | '/food/checkout'
    | '/food/dishes'
    | '/food/favourites'
    | '/food/offers'
    | '/furniture/$id'
    | '/p/$id'
    | '/food/'
    | '/furniture/'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/furniture'
    | '/admin/furniture-promos'
    | '/admin/hero-slides'
    | '/admin/inventory'
    | '/admin/offer-tiles'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/refunds-verify'
    | '/admin/reports'
    | '/admin/restaurants'
    | '/admin/riders'
    | '/admin/team'
    | '/admin/warehouses'
    | '/food/orders'
    | '/orders/$id'
    | '/outlet/menu'
    | '/outlet/orders'
    | '/outlet/refunds'
    | '/partner/managers'
    | '/partner/menu'
    | '/partner/orders'
    | '/partner/outlets'
    | '/partner/payouts'
    | '/partner/profile'
    | '/api/public/razorpay-webhook'
    | '/food/r/$slug'
    | '/admin/'
    | '/outlet/'
    | '/partner/'
    | '/orders/$id/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/login'
    | '/order-success'
    | '/search'
    | '/support'
    | '/wishlist'
    | '/account'
    | '/notifications'
    | '/orders'
    | '/c/$slug'
    | '/debug/php-mode'
    | '/food/cart'
    | '/food/checkout'
    | '/food/dishes'
    | '/food/favourites'
    | '/food/offers'
    | '/furniture/$id'
    | '/p/$id'
    | '/food'
    | '/furniture'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/furniture'
    | '/admin/furniture-promos'
    | '/admin/hero-slides'
    | '/admin/inventory'
    | '/admin/offer-tiles'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/refunds-verify'
    | '/admin/reports'
    | '/admin/restaurants'
    | '/admin/riders'
    | '/admin/team'
    | '/admin/warehouses'
    | '/food/orders'
    | '/orders/$id'
    | '/outlet/menu'
    | '/outlet/orders'
    | '/outlet/refunds'
    | '/partner/managers'
    | '/partner/menu'
    | '/partner/orders'
    | '/partner/outlets'
    | '/partner/payouts'
    | '/partner/profile'
    | '/api/public/razorpay-webhook'
    | '/food/r/$slug'
    | '/admin'
    | '/outlet'
    | '/partner'
    | '/orders/$id/invoice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/login'
    | '/order-success'
    | '/search'
    | '/support'
    | '/wishlist'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/outlet'
    | '/_authenticated/partner'
    | '/c/$slug'
    | '/debug/php-mode'
    | '/food/cart'
    | '/food/checkout'
    | '/food/dishes'
    | '/food/favourites'
    | '/food/offers'
    | '/furniture/$id'
    | '/p/$id'
    | '/food/'
    | '/furniture/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/furniture'
    | '/_authenticated/admin/furniture-promos'
    | '/_authenticated/admin/hero-slides'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/offer-tiles'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/refunds'
    | '/_authenticated/admin/refunds-verify'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/restaurants'
    | '/_authenticated/admin/riders'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/warehouses'
    | '/_authenticated/food/orders'
    | '/_authenticated/orders/$id'
    | '/_authenticated/outlet/menu'
    | '/_authenticated/outlet/orders'
    | '/_authenticated/outlet/refunds'
    | '/_authenticated/partner/managers'
    | '/_authenticated/partner/menu'
    | '/_authenticated/partner/orders'
    | '/_authenticated/partner/outlets'
    | '/_authenticated/partner/payouts'
    | '/_authenticated/partner/profile'
    | '/api/public/razorpay-webhook'
    | '/food/r/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/outlet/'
    | '/_authenticated/partner/'
    | '/_authenticated/orders/$id/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRoute
  WishlistRoute: typeof WishlistRoute
  CSlugRoute: typeof CSlugRoute
  DebugPhpModeRoute: typeof DebugPhpModeRoute
  FoodCartRoute: typeof FoodCartRoute
  FoodCheckoutRoute: typeof FoodCheckoutRoute
  FoodDishesRoute: typeof FoodDishesRoute
  FoodFavouritesRoute: typeof FoodFavouritesRoute
  FoodOffersRoute: typeof FoodOffersRoute
  FurnitureIdRoute: typeof FurnitureIdRoute
  PIdRoute: typeof PIdRoute
  FoodIndexRoute: typeof FoodIndexRoute
  FurnitureIndexRoute: typeof FurnitureIndexRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  FoodRSlugRoute: typeof FoodRSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furniture/': {
      id: '/furniture/'
      path: '/furniture'
      fullPath: '/furniture/'
      preLoaderRoute: typeof FurnitureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/': {
      id: '/food/'
      path: '/food'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furniture/$id': {
      id: '/furniture/$id'
      path: '/furniture/$id'
      fullPath: '/furniture/$id'
      preLoaderRoute: typeof FurnitureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/offers': {
      id: '/food/offers'
      path: '/food/offers'
      fullPath: '/food/offers'
      preLoaderRoute: typeof FoodOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/favourites': {
      id: '/food/favourites'
      path: '/food/favourites'
      fullPath: '/food/favourites'
      preLoaderRoute: typeof FoodFavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/dishes': {
      id: '/food/dishes'
      path: '/food/dishes'
      fullPath: '/food/dishes'
      preLoaderRoute: typeof FoodDishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/checkout': {
      id: '/food/checkout'
      path: '/food/checkout'
      fullPath: '/food/checkout'
      preLoaderRoute: typeof FoodCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/cart': {
      id: '/food/cart'
      path: '/food/cart'
      fullPath: '/food/cart'
      preLoaderRoute: typeof FoodCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/php-mode': {
      id: '/debug/php-mode'
      path: '/debug/php-mode'
      fullPath: '/debug/php-mode'
      preLoaderRoute: typeof DebugPhpModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outlet': {
      id: '/_authenticated/outlet'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof AuthenticatedOutletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partner/': {
      id: '/_authenticated/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof AuthenticatedPartnerIndexRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/outlet/': {
      id: '/_authenticated/outlet/'
      path: '/'
      fullPath: '/outlet/'
      preLoaderRoute: typeof AuthenticatedOutletIndexRouteImport
      parentRoute: typeof AuthenticatedOutletRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/food/r/$slug': {
      id: '/food/r/$slug'
      path: '/food/r/$slug'
      fullPath: '/food/r/$slug'
      preLoaderRoute: typeof FoodRSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/partner/profile': {
      id: '/_authenticated/partner/profile'
      path: '/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof AuthenticatedPartnerProfileRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/payouts': {
      id: '/_authenticated/partner/payouts'
      path: '/payouts'
      fullPath: '/partner/payouts'
      preLoaderRoute: typeof AuthenticatedPartnerPayoutsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/outlets': {
      id: '/_authenticated/partner/outlets'
      path: '/outlets'
      fullPath: '/partner/outlets'
      preLoaderRoute: typeof AuthenticatedPartnerOutletsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/orders': {
      id: '/_authenticated/partner/orders'
      path: '/orders'
      fullPath: '/partner/orders'
      preLoaderRoute: typeof AuthenticatedPartnerOrdersRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/menu': {
      id: '/_authenticated/partner/menu'
      path: '/menu'
      fullPath: '/partner/menu'
      preLoaderRoute: typeof AuthenticatedPartnerMenuRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/managers': {
      id: '/_authenticated/partner/managers'
      path: '/managers'
      fullPath: '/partner/managers'
      preLoaderRoute: typeof AuthenticatedPartnerManagersRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/outlet/refunds': {
      id: '/_authenticated/outlet/refunds'
      path: '/refunds'
      fullPath: '/outlet/refunds'
      preLoaderRoute: typeof AuthenticatedOutletRefundsRouteImport
      parentRoute: typeof AuthenticatedOutletRoute
    }
    '/_authenticated/outlet/orders': {
      id: '/_authenticated/outlet/orders'
      path: '/orders'
      fullPath: '/outlet/orders'
      preLoaderRoute: typeof AuthenticatedOutletOrdersRouteImport
      parentRoute: typeof AuthenticatedOutletRoute
    }
    '/_authenticated/outlet/menu': {
      id: '/_authenticated/outlet/menu'
      path: '/menu'
      fullPath: '/outlet/menu'
      preLoaderRoute: typeof AuthenticatedOutletMenuRouteImport
      parentRoute: typeof AuthenticatedOutletRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/food/orders': {
      id: '/_authenticated/food/orders'
      path: '/food/orders'
      fullPath: '/food/orders'
      preLoaderRoute: typeof AuthenticatedFoodOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/warehouses': {
      id: '/_authenticated/admin/warehouses'
      path: '/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AuthenticatedAdminWarehousesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/riders': {
      id: '/_authenticated/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AuthenticatedAdminRidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants': {
      id: '/_authenticated/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/refunds-verify': {
      id: '/_authenticated/admin/refunds-verify'
      path: '/refunds-verify'
      fullPath: '/admin/refunds-verify'
      preLoaderRoute: typeof AuthenticatedAdminRefundsVerifyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/refunds': {
      id: '/_authenticated/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AuthenticatedAdminRefundsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offer-tiles': {
      id: '/_authenticated/admin/offer-tiles'
      path: '/offer-tiles'
      fullPath: '/admin/offer-tiles'
      preLoaderRoute: typeof AuthenticatedAdminOfferTilesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hero-slides': {
      id: '/_authenticated/admin/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AuthenticatedAdminHeroSlidesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/furniture-promos': {
      id: '/_authenticated/admin/furniture-promos'
      path: '/furniture-promos'
      fullPath: '/admin/furniture-promos'
      preLoaderRoute: typeof AuthenticatedAdminFurniturePromosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/furniture': {
      id: '/_authenticated/admin/furniture'
      path: '/furniture'
      fullPath: '/admin/furniture'
      preLoaderRoute: typeof AuthenticatedAdminFurnitureRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/orders/$id/invoice': {
      id: '/_authenticated/orders/$id/invoice'
      path: '/invoice'
      fullPath: '/orders/$id/invoice'
      preLoaderRoute: typeof AuthenticatedOrdersIdInvoiceRouteImport
      parentRoute: typeof AuthenticatedOrdersIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminFurnitureRoute: typeof AuthenticatedAdminFurnitureRoute
  AuthenticatedAdminFurniturePromosRoute: typeof AuthenticatedAdminFurniturePromosRoute
  AuthenticatedAdminHeroSlidesRoute: typeof AuthenticatedAdminHeroSlidesRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminOfferTilesRoute: typeof AuthenticatedAdminOfferTilesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRefundsRoute: typeof AuthenticatedAdminRefundsRoute
  AuthenticatedAdminRefundsVerifyRoute: typeof AuthenticatedAdminRefundsVerifyRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRestaurantsRoute: typeof AuthenticatedAdminRestaurantsRoute
  AuthenticatedAdminRidersRoute: typeof AuthenticatedAdminRidersRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminWarehousesRoute: typeof AuthenticatedAdminWarehousesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminFurnitureRoute: AuthenticatedAdminFurnitureRoute,
  AuthenticatedAdminFurniturePromosRoute:
    AuthenticatedAdminFurniturePromosRoute,
  AuthenticatedAdminHeroSlidesRoute: AuthenticatedAdminHeroSlidesRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminOfferTilesRoute: AuthenticatedAdminOfferTilesRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminRefundsRoute: AuthenticatedAdminRefundsRoute,
  AuthenticatedAdminRefundsVerifyRoute: AuthenticatedAdminRefundsVerifyRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRestaurantsRoute: AuthenticatedAdminRestaurantsRoute,
  AuthenticatedAdminRidersRoute: AuthenticatedAdminRidersRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminWarehousesRoute: AuthenticatedAdminWarehousesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedOrdersIdRouteChildren {
  AuthenticatedOrdersIdInvoiceRoute: typeof AuthenticatedOrdersIdInvoiceRoute
}

const AuthenticatedOrdersIdRouteChildren: AuthenticatedOrdersIdRouteChildren = {
  AuthenticatedOrdersIdInvoiceRoute: AuthenticatedOrdersIdInvoiceRoute,
}

const AuthenticatedOrdersIdRouteWithChildren =
  AuthenticatedOrdersIdRoute._addFileChildren(
    AuthenticatedOrdersIdRouteChildren,
  )

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRouteWithChildren
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRouteWithChildren,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedOutletRouteChildren {
  AuthenticatedOutletMenuRoute: typeof AuthenticatedOutletMenuRoute
  AuthenticatedOutletOrdersRoute: typeof AuthenticatedOutletOrdersRoute
  AuthenticatedOutletRefundsRoute: typeof AuthenticatedOutletRefundsRoute
  AuthenticatedOutletIndexRoute: typeof AuthenticatedOutletIndexRoute
}

const AuthenticatedOutletRouteChildren: AuthenticatedOutletRouteChildren = {
  AuthenticatedOutletMenuRoute: AuthenticatedOutletMenuRoute,
  AuthenticatedOutletOrdersRoute: AuthenticatedOutletOrdersRoute,
  AuthenticatedOutletRefundsRoute: AuthenticatedOutletRefundsRoute,
  AuthenticatedOutletIndexRoute: AuthenticatedOutletIndexRoute,
}

const AuthenticatedOutletRouteWithChildren =
  AuthenticatedOutletRoute._addFileChildren(AuthenticatedOutletRouteChildren)

interface AuthenticatedPartnerRouteChildren {
  AuthenticatedPartnerManagersRoute: typeof AuthenticatedPartnerManagersRoute
  AuthenticatedPartnerMenuRoute: typeof AuthenticatedPartnerMenuRoute
  AuthenticatedPartnerOrdersRoute: typeof AuthenticatedPartnerOrdersRoute
  AuthenticatedPartnerOutletsRoute: typeof AuthenticatedPartnerOutletsRoute
  AuthenticatedPartnerPayoutsRoute: typeof AuthenticatedPartnerPayoutsRoute
  AuthenticatedPartnerProfileRoute: typeof AuthenticatedPartnerProfileRoute
  AuthenticatedPartnerIndexRoute: typeof AuthenticatedPartnerIndexRoute
}

const AuthenticatedPartnerRouteChildren: AuthenticatedPartnerRouteChildren = {
  AuthenticatedPartnerManagersRoute: AuthenticatedPartnerManagersRoute,
  AuthenticatedPartnerMenuRoute: AuthenticatedPartnerMenuRoute,
  AuthenticatedPartnerOrdersRoute: AuthenticatedPartnerOrdersRoute,
  AuthenticatedPartnerOutletsRoute: AuthenticatedPartnerOutletsRoute,
  AuthenticatedPartnerPayoutsRoute: AuthenticatedPartnerPayoutsRoute,
  AuthenticatedPartnerProfileRoute: AuthenticatedPartnerProfileRoute,
  AuthenticatedPartnerIndexRoute: AuthenticatedPartnerIndexRoute,
}

const AuthenticatedPartnerRouteWithChildren =
  AuthenticatedPartnerRoute._addFileChildren(AuthenticatedPartnerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedOutletRoute: typeof AuthenticatedOutletRouteWithChildren
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRouteWithChildren
  AuthenticatedFoodOrdersRoute: typeof AuthenticatedFoodOrdersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedOutletRoute: AuthenticatedOutletRouteWithChildren,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRouteWithChildren,
  AuthenticatedFoodOrdersRoute: AuthenticatedFoodOrdersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRoute,
  WishlistRoute: WishlistRoute,
  CSlugRoute: CSlugRoute,
  DebugPhpModeRoute: DebugPhpModeRoute,
  FoodCartRoute: FoodCartRoute,
  FoodCheckoutRoute: FoodCheckoutRoute,
  FoodDishesRoute: FoodDishesRoute,
  FoodFavouritesRoute: FoodFavouritesRoute,
  FoodOffersRoute: FoodOffersRoute,
  FurnitureIdRoute: FurnitureIdRoute,
  PIdRoute: PIdRoute,
  FoodIndexRoute: FoodIndexRoute,
  FurnitureIndexRoute: FurnitureIndexRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  FoodRSlugRoute: FoodRSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
